### ISSUE TITLE
Customer registration issue 

### ISSUE THREAD

**Issue by ilearnbydoing** [twisted1919/mailwizz-php-sdk#11]
If you follow example customers.php file it register a user without default group and also register as an active customer rather pending-confirm.

Can you look into this and update the SDK?

thanks

**Comment by twisted1919** [comment]
@w3update - The status is set to active if you don't require approval of the accounts from the app settings, so check that (see /apps/api/controllers/CustomersController.php Line 64). Otherwise is set to pending.

As for the group, this is by design, you can't have customer put themselves in groups as they want.

**Comment by ilearnbydoing** [comment]
I understand.
currently the API is supported at customer level. right?
Is there no Extended-API to only be issue from backend with extra features?
may this help to accomplish task like webhook service (for real time CRM/payment gateway data integration)

**Comment by twisted1919** [comment]
> currently the API is supported at customer level. right?  

This is correct yes.

> Is there no Extended-API to only be issue from backend with extra features?  

Nope, and we don't plan for this. But you can as well extend the current API with your endpoints to target the backend.
